# Change these first
owner: AlignedCookie88 # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: AlignedCookie88 Website
    url: https://alignedcookie88.com
  - name: DFAuth
    url: https://dfauth.alignedcookie88.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.alignedcookie88.com
  # baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AlignedCookie88 Website Status
  introTitle: "**Welcome.**"
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: AlignedCookie88 Website
      href: https://alignedcookie88.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
